name: PR Check

on: [pull_request]

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest ]

    steps:
    - name: Check out
      uses: actions/checkout@v3
      with:
        submodules: 'recursive'
    - name: Setup protoc
      uses: arduino/setup-protoc@v1.1.2
    - name: Check
      run: cargo check
